import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :rs, RsWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  check_origin: [
    "https://delivery-demo-6hrmbwesca-wm.a.run.app",
    "https://delivery.demo.gojourney.dev",
    "https://jourdash.demo.gojourney.dev",
    "//localhost"
  ]

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

config :journey, log_level: :warning
config :journey, :background_sweeper, period_seconds: 5

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
